name: "Podcast Generator"
author: "Ugochi Ukaegbu"
description: "Generates a podacst feed from a yml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email: 
    description: "Email address of the user who wants to make use of the generator"
    required: True
    default: ${{ github.actor }}@localhost
  name:
    description: "Name of the user who wants to make use of the generator"
    required: True
    default: ${{ github.actor }}
